version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:3.7.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"  # Puerto interno para comunicación entre contenedores
      - "9093:9093"  # Puerto externo para clientes externos
    networks:
      - kafka-network

  spark:
    image: bitnami/spark:3.4.0
    container_name: spark
    depends_on:
      - kafka
    environment:
      SPARK_MODE: "master"
    command: bash -c "while ! ls /opt/app/processor.py; do sleep 1; done && spark-submit --master local[2] /opt/app/processor.py"
    volumes:
      - ./processor.py:/opt/app/processor.py
    networks:
      - kafka-network

  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra-init.cql:/docker-entrypoint-initdb.d/init.cql
    networks:
      - kafka-network

  elasticsearch:
    image: elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - kafka-network

  kibana:
    image: kibana:8.5.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - kafka-network

  scrapper:
    image: python:3.9
    container_name: scrapper
    depends_on:
      - kafka
    volumes:
      - ./scrapper.py:/app/scrapper.py
    working_dir: /app
    command: python scrapper.py
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
