version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_ENABLE_AUTH: "no"
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:3.7.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092" 
    networks:
      - kafka-network

  spark-master:
    image: bitnami/spark:3.4.0
    container_name: spark-master
    environment:
      SPARK_MODE: "master"
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
      ALLOW_ANONYMOUS_LOGIN: "yes"
      SPARK_MASTER_HOST: "spark-master"  # Aquí forzamos el hostname
      SPARK_LOCAL_HOSTNAME: "spark-master"
    ports:
      - "8080:8080"  # UI del Spark Master
      - "7077:7077" 
    networks:
      - kafka-network

  spark-worker:
    image: bitnami/spark:3.4.0
    container_name: spark-worker
    environment:
      SPARK_MODE: "worker"
      SPARK_MASTER_URL: "spark://spark-master:7077"
      ALLOW_ANONYMOUS_LOGIN: "yes"
    depends_on:
      - spark-master
    networks:
      - kafka-network

  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=waze_cluster
      - CASSANDRA_SEEDS=cassandra
    networks:
      - kafka-network

  elasticsearch:
    image: elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - kafka-network

  kibana:
    image: kibana:8.5.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
