version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # Ensure Kafka listens locally
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092              # Bind to all network interfaces
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  spark:
    image: bitnami/spark:latest
    depends_on:
      - kafka
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
    command: spark-submit --master local[2] /opt/app/processor.py
    volumes:
      - ./processor.py:/opt/app/processor.py

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra-init.cql:/docker-entrypoint-initdb.d/init.cql

  elasticsearch:
    image: elasticsearch:8.5.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.5.0
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"

  scrapper:
    image: python:3.9
    depends_on:
      - kafka
    volumes:
      - ./scrapper.py:/app/scrapper.py
    working_dir: /app
    command: python scrapper.py
